# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nonononoki/_DEV/ddcui

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nonononoki/_DEV/ddcui

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nonononoki/_DEV/ddcui/CMakeFiles /home/nonononoki/_DEV/ddcui//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nonononoki/_DEV/ddcui/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named ddcui

# Build rule for target.
ddcui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ddcui
.PHONY : ddcui

# fast build rule for target.
ddcui/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/build
.PHONY : ddcui/fast

#=============================================================================
# Target rules for targets named ddcui_autogen

# Build rule for target.
ddcui_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ddcui_autogen
.PHONY : ddcui_autogen

# fast build rule for target.
ddcui_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui_autogen.dir/build.make CMakeFiles/ddcui_autogen.dir/build
.PHONY : ddcui_autogen/fast

ddcui_autogen/EWIEGA46WW/qrc_ddcui.o: ddcui_autogen/EWIEGA46WW/qrc_ddcui.cpp.o

.PHONY : ddcui_autogen/EWIEGA46WW/qrc_ddcui.o

# target to build an object file
ddcui_autogen/EWIEGA46WW/qrc_ddcui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/ddcui_autogen/EWIEGA46WW/qrc_ddcui.cpp.o
.PHONY : ddcui_autogen/EWIEGA46WW/qrc_ddcui.cpp.o

ddcui_autogen/EWIEGA46WW/qrc_ddcui.i: ddcui_autogen/EWIEGA46WW/qrc_ddcui.cpp.i

.PHONY : ddcui_autogen/EWIEGA46WW/qrc_ddcui.i

# target to preprocess a source file
ddcui_autogen/EWIEGA46WW/qrc_ddcui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/ddcui_autogen/EWIEGA46WW/qrc_ddcui.cpp.i
.PHONY : ddcui_autogen/EWIEGA46WW/qrc_ddcui.cpp.i

ddcui_autogen/EWIEGA46WW/qrc_ddcui.s: ddcui_autogen/EWIEGA46WW/qrc_ddcui.cpp.s

.PHONY : ddcui_autogen/EWIEGA46WW/qrc_ddcui.s

# target to generate assembly for a file
ddcui_autogen/EWIEGA46WW/qrc_ddcui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/ddcui_autogen/EWIEGA46WW/qrc_ddcui.cpp.s
.PHONY : ddcui_autogen/EWIEGA46WW/qrc_ddcui.cpp.s

ddcui_autogen/mocs_compilation.o: ddcui_autogen/mocs_compilation.cpp.o

.PHONY : ddcui_autogen/mocs_compilation.o

# target to build an object file
ddcui_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/ddcui_autogen/mocs_compilation.cpp.o
.PHONY : ddcui_autogen/mocs_compilation.cpp.o

ddcui_autogen/mocs_compilation.i: ddcui_autogen/mocs_compilation.cpp.i

.PHONY : ddcui_autogen/mocs_compilation.i

# target to preprocess a source file
ddcui_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/ddcui_autogen/mocs_compilation.cpp.i
.PHONY : ddcui_autogen/mocs_compilation.cpp.i

ddcui_autogen/mocs_compilation.s: ddcui_autogen/mocs_compilation.cpp.s

.PHONY : ddcui_autogen/mocs_compilation.s

# target to generate assembly for a file
ddcui_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/ddcui_autogen/mocs_compilation.cpp.s
.PHONY : ddcui_autogen/mocs_compilation.cpp.s

src/action_dialogs/debug_actions_dialog.o: src/action_dialogs/debug_actions_dialog.cpp.o

.PHONY : src/action_dialogs/debug_actions_dialog.o

# target to build an object file
src/action_dialogs/debug_actions_dialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/action_dialogs/debug_actions_dialog.cpp.o
.PHONY : src/action_dialogs/debug_actions_dialog.cpp.o

src/action_dialogs/debug_actions_dialog.i: src/action_dialogs/debug_actions_dialog.cpp.i

.PHONY : src/action_dialogs/debug_actions_dialog.i

# target to preprocess a source file
src/action_dialogs/debug_actions_dialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/action_dialogs/debug_actions_dialog.cpp.i
.PHONY : src/action_dialogs/debug_actions_dialog.cpp.i

src/action_dialogs/debug_actions_dialog.s: src/action_dialogs/debug_actions_dialog.cpp.s

.PHONY : src/action_dialogs/debug_actions_dialog.s

# target to generate assembly for a file
src/action_dialogs/debug_actions_dialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/action_dialogs/debug_actions_dialog.cpp.s
.PHONY : src/action_dialogs/debug_actions_dialog.cpp.s

src/base/core.o: src/base/core.cpp.o

.PHONY : src/base/core.o

# target to build an object file
src/base/core.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/base/core.cpp.o
.PHONY : src/base/core.cpp.o

src/base/core.i: src/base/core.cpp.i

.PHONY : src/base/core.i

# target to preprocess a source file
src/base/core.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/base/core.cpp.i
.PHONY : src/base/core.cpp.i

src/base/core.s: src/base/core.cpp.s

.PHONY : src/base/core.s

# target to generate assembly for a file
src/base/core.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/base/core.cpp.s
.PHONY : src/base/core.cpp.s

src/base/ddca_utils.o: src/base/ddca_utils.cpp.o

.PHONY : src/base/ddca_utils.o

# target to build an object file
src/base/ddca_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/base/ddca_utils.cpp.o
.PHONY : src/base/ddca_utils.cpp.o

src/base/ddca_utils.i: src/base/ddca_utils.cpp.i

.PHONY : src/base/ddca_utils.i

# target to preprocess a source file
src/base/ddca_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/base/ddca_utils.cpp.i
.PHONY : src/base/ddca_utils.cpp.i

src/base/ddca_utils.s: src/base/ddca_utils.cpp.s

.PHONY : src/base/ddca_utils.s

# target to generate assembly for a file
src/base/ddca_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/base/ddca_utils.cpp.s
.PHONY : src/base/ddca_utils.cpp.s

src/base/ddcui_parms.o: src/base/ddcui_parms.cpp.o

.PHONY : src/base/ddcui_parms.o

# target to build an object file
src/base/ddcui_parms.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/base/ddcui_parms.cpp.o
.PHONY : src/base/ddcui_parms.cpp.o

src/base/ddcui_parms.i: src/base/ddcui_parms.cpp.i

.PHONY : src/base/ddcui_parms.i

# target to preprocess a source file
src/base/ddcui_parms.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/base/ddcui_parms.cpp.i
.PHONY : src/base/ddcui_parms.cpp.i

src/base/ddcui_parms.s: src/base/ddcui_parms.cpp.s

.PHONY : src/base/ddcui_parms.s

# target to generate assembly for a file
src/base/ddcui_parms.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/base/ddcui_parms.cpp.s
.PHONY : src/base/ddcui_parms.cpp.s

src/base/feature_list.o: src/base/feature_list.c.o

.PHONY : src/base/feature_list.o

# target to build an object file
src/base/feature_list.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/base/feature_list.c.o
.PHONY : src/base/feature_list.c.o

src/base/feature_list.i: src/base/feature_list.c.i

.PHONY : src/base/feature_list.i

# target to preprocess a source file
src/base/feature_list.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/base/feature_list.c.i
.PHONY : src/base/feature_list.c.i

src/base/feature_list.s: src/base/feature_list.c.s

.PHONY : src/base/feature_list.s

# target to generate assembly for a file
src/base/feature_list.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/base/feature_list.c.s
.PHONY : src/base/feature_list.c.s

src/base/feature_selector.o: src/base/feature_selector.cpp.o

.PHONY : src/base/feature_selector.o

# target to build an object file
src/base/feature_selector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/base/feature_selector.cpp.o
.PHONY : src/base/feature_selector.cpp.o

src/base/feature_selector.i: src/base/feature_selector.cpp.i

.PHONY : src/base/feature_selector.i

# target to preprocess a source file
src/base/feature_selector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/base/feature_selector.cpp.i
.PHONY : src/base/feature_selector.cpp.i

src/base/feature_selector.s: src/base/feature_selector.cpp.s

.PHONY : src/base/feature_selector.s

# target to generate assembly for a file
src/base/feature_selector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/base/feature_selector.cpp.s
.PHONY : src/base/feature_selector.cpp.s

src/base/global_state.o: src/base/global_state.cpp.o

.PHONY : src/base/global_state.o

# target to build an object file
src/base/global_state.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/base/global_state.cpp.o
.PHONY : src/base/global_state.cpp.o

src/base/global_state.i: src/base/global_state.cpp.i

.PHONY : src/base/global_state.i

# target to preprocess a source file
src/base/global_state.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/base/global_state.cpp.i
.PHONY : src/base/global_state.cpp.i

src/base/global_state.s: src/base/global_state.cpp.s

.PHONY : src/base/global_state.s

# target to generate assembly for a file
src/base/global_state.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/base/global_state.cpp.s
.PHONY : src/base/global_state.cpp.s

src/base/other_options_state.o: src/base/other_options_state.cpp.o

.PHONY : src/base/other_options_state.o

# target to build an object file
src/base/other_options_state.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/base/other_options_state.cpp.o
.PHONY : src/base/other_options_state.cpp.o

src/base/other_options_state.i: src/base/other_options_state.cpp.i

.PHONY : src/base/other_options_state.i

# target to preprocess a source file
src/base/other_options_state.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/base/other_options_state.cpp.i
.PHONY : src/base/other_options_state.cpp.i

src/base/other_options_state.s: src/base/other_options_state.cpp.s

.PHONY : src/base/other_options_state.s

# target to generate assembly for a file
src/base/other_options_state.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/base/other_options_state.cpp.s
.PHONY : src/base/other_options_state.cpp.s

src/base/user_interface_options_state.o: src/base/user_interface_options_state.cpp.o

.PHONY : src/base/user_interface_options_state.o

# target to build an object file
src/base/user_interface_options_state.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/base/user_interface_options_state.cpp.o
.PHONY : src/base/user_interface_options_state.cpp.o

src/base/user_interface_options_state.i: src/base/user_interface_options_state.cpp.i

.PHONY : src/base/user_interface_options_state.i

# target to preprocess a source file
src/base/user_interface_options_state.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/base/user_interface_options_state.cpp.i
.PHONY : src/base/user_interface_options_state.cpp.i

src/base/user_interface_options_state.s: src/base/user_interface_options_state.cpp.s

.PHONY : src/base/user_interface_options_state.s

# target to generate assembly for a file
src/base/user_interface_options_state.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/base/user_interface_options_state.cpp.s
.PHONY : src/base/user_interface_options_state.cpp.s

src/base/widget_debug.o: src/base/widget_debug.cpp.o

.PHONY : src/base/widget_debug.o

# target to build an object file
src/base/widget_debug.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/base/widget_debug.cpp.o
.PHONY : src/base/widget_debug.cpp.o

src/base/widget_debug.i: src/base/widget_debug.cpp.i

.PHONY : src/base/widget_debug.i

# target to preprocess a source file
src/base/widget_debug.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/base/widget_debug.cpp.i
.PHONY : src/base/widget_debug.cpp.i

src/base/widget_debug.s: src/base/widget_debug.cpp.s

.PHONY : src/base/widget_debug.s

# target to generate assembly for a file
src/base/widget_debug.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/base/widget_debug.cpp.s
.PHONY : src/base/widget_debug.cpp.s

src/c_util/data_structures.o: src/c_util/data_structures.c.o

.PHONY : src/c_util/data_structures.o

# target to build an object file
src/c_util/data_structures.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/c_util/data_structures.c.o
.PHONY : src/c_util/data_structures.c.o

src/c_util/data_structures.i: src/c_util/data_structures.c.i

.PHONY : src/c_util/data_structures.i

# target to preprocess a source file
src/c_util/data_structures.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/c_util/data_structures.c.i
.PHONY : src/c_util/data_structures.c.i

src/c_util/data_structures.s: src/c_util/data_structures.c.s

.PHONY : src/c_util/data_structures.s

# target to generate assembly for a file
src/c_util/data_structures.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/c_util/data_structures.c.s
.PHONY : src/c_util/data_structures.c.s

src/c_util/string_util.o: src/c_util/string_util.c.o

.PHONY : src/c_util/string_util.o

# target to build an object file
src/c_util/string_util.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/c_util/string_util.c.o
.PHONY : src/c_util/string_util.c.o

src/c_util/string_util.i: src/c_util/string_util.c.i

.PHONY : src/c_util/string_util.i

# target to preprocess a source file
src/c_util/string_util.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/c_util/string_util.c.i
.PHONY : src/c_util/string_util.c.i

src/c_util/string_util.s: src/c_util/string_util.c.s

.PHONY : src/c_util/string_util.s

# target to generate assembly for a file
src/c_util/string_util.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/c_util/string_util.c.s
.PHONY : src/c_util/string_util.c.s

src/cmdline/cmd_parser.o: src/cmdline/cmd_parser.c.o

.PHONY : src/cmdline/cmd_parser.o

# target to build an object file
src/cmdline/cmd_parser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/cmdline/cmd_parser.c.o
.PHONY : src/cmdline/cmd_parser.c.o

src/cmdline/cmd_parser.i: src/cmdline/cmd_parser.c.i

.PHONY : src/cmdline/cmd_parser.i

# target to preprocess a source file
src/cmdline/cmd_parser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/cmdline/cmd_parser.c.i
.PHONY : src/cmdline/cmd_parser.c.i

src/cmdline/cmd_parser.s: src/cmdline/cmd_parser.c.s

.PHONY : src/cmdline/cmd_parser.s

# target to generate assembly for a file
src/cmdline/cmd_parser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/cmdline/cmd_parser.c.s
.PHONY : src/cmdline/cmd_parser.c.s

src/cmdline/cmd_parser_aux.o: src/cmdline/cmd_parser_aux.c.o

.PHONY : src/cmdline/cmd_parser_aux.o

# target to build an object file
src/cmdline/cmd_parser_aux.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/cmdline/cmd_parser_aux.c.o
.PHONY : src/cmdline/cmd_parser_aux.c.o

src/cmdline/cmd_parser_aux.i: src/cmdline/cmd_parser_aux.c.i

.PHONY : src/cmdline/cmd_parser_aux.i

# target to preprocess a source file
src/cmdline/cmd_parser_aux.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/cmdline/cmd_parser_aux.c.i
.PHONY : src/cmdline/cmd_parser_aux.c.i

src/cmdline/cmd_parser_aux.s: src/cmdline/cmd_parser_aux.c.s

.PHONY : src/cmdline/cmd_parser_aux.s

# target to generate assembly for a file
src/cmdline/cmd_parser_aux.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/cmdline/cmd_parser_aux.c.s
.PHONY : src/cmdline/cmd_parser_aux.c.s

src/cmdline/parsed_cmd.o: src/cmdline/parsed_cmd.c.o

.PHONY : src/cmdline/parsed_cmd.o

# target to build an object file
src/cmdline/parsed_cmd.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/cmdline/parsed_cmd.c.o
.PHONY : src/cmdline/parsed_cmd.c.o

src/cmdline/parsed_cmd.i: src/cmdline/parsed_cmd.c.i

.PHONY : src/cmdline/parsed_cmd.i

# target to preprocess a source file
src/cmdline/parsed_cmd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/cmdline/parsed_cmd.c.i
.PHONY : src/cmdline/parsed_cmd.c.i

src/cmdline/parsed_cmd.s: src/cmdline/parsed_cmd.c.s

.PHONY : src/cmdline/parsed_cmd.s

# target to generate assembly for a file
src/cmdline/parsed_cmd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/cmdline/parsed_cmd.c.s
.PHONY : src/cmdline/parsed_cmd.c.s

src/core_widgets/enhanced_slider.o: src/core_widgets/enhanced_slider.cpp.o

.PHONY : src/core_widgets/enhanced_slider.o

# target to build an object file
src/core_widgets/enhanced_slider.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/core_widgets/enhanced_slider.cpp.o
.PHONY : src/core_widgets/enhanced_slider.cpp.o

src/core_widgets/enhanced_slider.i: src/core_widgets/enhanced_slider.cpp.i

.PHONY : src/core_widgets/enhanced_slider.i

# target to preprocess a source file
src/core_widgets/enhanced_slider.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/core_widgets/enhanced_slider.cpp.i
.PHONY : src/core_widgets/enhanced_slider.cpp.i

src/core_widgets/enhanced_slider.s: src/core_widgets/enhanced_slider.cpp.s

.PHONY : src/core_widgets/enhanced_slider.s

# target to generate assembly for a file
src/core_widgets/enhanced_slider.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/core_widgets/enhanced_slider.cpp.s
.PHONY : src/core_widgets/enhanced_slider.cpp.s

src/core_widgets/hex_number_validator.o: src/core_widgets/hex_number_validator.cpp.o

.PHONY : src/core_widgets/hex_number_validator.o

# target to build an object file
src/core_widgets/hex_number_validator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/core_widgets/hex_number_validator.cpp.o
.PHONY : src/core_widgets/hex_number_validator.cpp.o

src/core_widgets/hex_number_validator.i: src/core_widgets/hex_number_validator.cpp.i

.PHONY : src/core_widgets/hex_number_validator.i

# target to preprocess a source file
src/core_widgets/hex_number_validator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/core_widgets/hex_number_validator.cpp.i
.PHONY : src/core_widgets/hex_number_validator.cpp.i

src/core_widgets/hex_number_validator.s: src/core_widgets/hex_number_validator.cpp.s

.PHONY : src/core_widgets/hex_number_validator.s

# target to generate assembly for a file
src/core_widgets/hex_number_validator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/core_widgets/hex_number_validator.cpp.s
.PHONY : src/core_widgets/hex_number_validator.cpp.s

src/core_widgets/hline_widget.o: src/core_widgets/hline_widget.cpp.o

.PHONY : src/core_widgets/hline_widget.o

# target to build an object file
src/core_widgets/hline_widget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/core_widgets/hline_widget.cpp.o
.PHONY : src/core_widgets/hline_widget.cpp.o

src/core_widgets/hline_widget.i: src/core_widgets/hline_widget.cpp.i

.PHONY : src/core_widgets/hline_widget.i

# target to preprocess a source file
src/core_widgets/hline_widget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/core_widgets/hline_widget.cpp.i
.PHONY : src/core_widgets/hline_widget.cpp.i

src/core_widgets/hline_widget.s: src/core_widgets/hline_widget.cpp.s

.PHONY : src/core_widgets/hline_widget.s

# target to generate assembly for a file
src/core_widgets/hline_widget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/core_widgets/hline_widget.cpp.s
.PHONY : src/core_widgets/hline_widget.cpp.s

src/core_widgets/number_entry_widget.o: src/core_widgets/number_entry_widget.cpp.o

.PHONY : src/core_widgets/number_entry_widget.o

# target to build an object file
src/core_widgets/number_entry_widget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/core_widgets/number_entry_widget.cpp.o
.PHONY : src/core_widgets/number_entry_widget.cpp.o

src/core_widgets/number_entry_widget.i: src/core_widgets/number_entry_widget.cpp.i

.PHONY : src/core_widgets/number_entry_widget.i

# target to preprocess a source file
src/core_widgets/number_entry_widget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/core_widgets/number_entry_widget.cpp.i
.PHONY : src/core_widgets/number_entry_widget.cpp.i

src/core_widgets/number_entry_widget.s: src/core_widgets/number_entry_widget.cpp.s

.PHONY : src/core_widgets/number_entry_widget.s

# target to generate assembly for a file
src/core_widgets/number_entry_widget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/core_widgets/number_entry_widget.cpp.s
.PHONY : src/core_widgets/number_entry_widget.cpp.s

src/feature_scrollarea/feature_widget.o: src/feature_scrollarea/feature_widget.cpp.o

.PHONY : src/feature_scrollarea/feature_widget.o

# target to build an object file
src/feature_scrollarea/feature_widget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/feature_scrollarea/feature_widget.cpp.o
.PHONY : src/feature_scrollarea/feature_widget.cpp.o

src/feature_scrollarea/feature_widget.i: src/feature_scrollarea/feature_widget.cpp.i

.PHONY : src/feature_scrollarea/feature_widget.i

# target to preprocess a source file
src/feature_scrollarea/feature_widget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/feature_scrollarea/feature_widget.cpp.i
.PHONY : src/feature_scrollarea/feature_widget.cpp.i

src/feature_scrollarea/feature_widget.s: src/feature_scrollarea/feature_widget.cpp.s

.PHONY : src/feature_scrollarea/feature_widget.s

# target to generate assembly for a file
src/feature_scrollarea/feature_widget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/feature_scrollarea/feature_widget.cpp.s
.PHONY : src/feature_scrollarea/feature_widget.cpp.s

src/feature_scrollarea/feature_widget_header.o: src/feature_scrollarea/feature_widget_header.cpp.o

.PHONY : src/feature_scrollarea/feature_widget_header.o

# target to build an object file
src/feature_scrollarea/feature_widget_header.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/feature_scrollarea/feature_widget_header.cpp.o
.PHONY : src/feature_scrollarea/feature_widget_header.cpp.o

src/feature_scrollarea/feature_widget_header.i: src/feature_scrollarea/feature_widget_header.cpp.i

.PHONY : src/feature_scrollarea/feature_widget_header.i

# target to preprocess a source file
src/feature_scrollarea/feature_widget_header.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/feature_scrollarea/feature_widget_header.cpp.i
.PHONY : src/feature_scrollarea/feature_widget_header.cpp.i

src/feature_scrollarea/feature_widget_header.s: src/feature_scrollarea/feature_widget_header.cpp.s

.PHONY : src/feature_scrollarea/feature_widget_header.s

# target to generate assembly for a file
src/feature_scrollarea/feature_widget_header.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/feature_scrollarea/feature_widget_header.cpp.s
.PHONY : src/feature_scrollarea/feature_widget_header.cpp.s

src/feature_scrollarea/features_scrollarea.o: src/feature_scrollarea/features_scrollarea.cpp.o

.PHONY : src/feature_scrollarea/features_scrollarea.o

# target to build an object file
src/feature_scrollarea/features_scrollarea.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/feature_scrollarea/features_scrollarea.cpp.o
.PHONY : src/feature_scrollarea/features_scrollarea.cpp.o

src/feature_scrollarea/features_scrollarea.i: src/feature_scrollarea/features_scrollarea.cpp.i

.PHONY : src/feature_scrollarea/features_scrollarea.i

# target to preprocess a source file
src/feature_scrollarea/features_scrollarea.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/feature_scrollarea/features_scrollarea.cpp.i
.PHONY : src/feature_scrollarea/features_scrollarea.cpp.i

src/feature_scrollarea/features_scrollarea.s: src/feature_scrollarea/features_scrollarea.cpp.s

.PHONY : src/feature_scrollarea/features_scrollarea.s

# target to generate assembly for a file
src/feature_scrollarea/features_scrollarea.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/feature_scrollarea/features_scrollarea.cpp.s
.PHONY : src/feature_scrollarea/features_scrollarea.cpp.s

src/feature_scrollarea/features_scrollarea_contents.o: src/feature_scrollarea/features_scrollarea_contents.cpp.o

.PHONY : src/feature_scrollarea/features_scrollarea_contents.o

# target to build an object file
src/feature_scrollarea/features_scrollarea_contents.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/feature_scrollarea/features_scrollarea_contents.cpp.o
.PHONY : src/feature_scrollarea/features_scrollarea_contents.cpp.o

src/feature_scrollarea/features_scrollarea_contents.i: src/feature_scrollarea/features_scrollarea_contents.cpp.i

.PHONY : src/feature_scrollarea/features_scrollarea_contents.i

# target to preprocess a source file
src/feature_scrollarea/features_scrollarea_contents.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/feature_scrollarea/features_scrollarea_contents.cpp.i
.PHONY : src/feature_scrollarea/features_scrollarea_contents.cpp.i

src/feature_scrollarea/features_scrollarea_contents.s: src/feature_scrollarea/features_scrollarea_contents.cpp.s

.PHONY : src/feature_scrollarea/features_scrollarea_contents.s

# target to generate assembly for a file
src/feature_scrollarea/features_scrollarea_contents.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/feature_scrollarea/features_scrollarea_contents.cpp.s
.PHONY : src/feature_scrollarea/features_scrollarea_contents.cpp.s

src/feature_scrollarea/features_scrollarea_ui.o: src/feature_scrollarea/features_scrollarea_ui.cpp.o

.PHONY : src/feature_scrollarea/features_scrollarea_ui.o

# target to build an object file
src/feature_scrollarea/features_scrollarea_ui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/feature_scrollarea/features_scrollarea_ui.cpp.o
.PHONY : src/feature_scrollarea/features_scrollarea_ui.cpp.o

src/feature_scrollarea/features_scrollarea_ui.i: src/feature_scrollarea/features_scrollarea_ui.cpp.i

.PHONY : src/feature_scrollarea/features_scrollarea_ui.i

# target to preprocess a source file
src/feature_scrollarea/features_scrollarea_ui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/feature_scrollarea/features_scrollarea_ui.cpp.i
.PHONY : src/feature_scrollarea/features_scrollarea_ui.cpp.i

src/feature_scrollarea/features_scrollarea_ui.s: src/feature_scrollarea/features_scrollarea_ui.cpp.s

.PHONY : src/feature_scrollarea/features_scrollarea_ui.s

# target to generate assembly for a file
src/feature_scrollarea/features_scrollarea_ui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/feature_scrollarea/features_scrollarea_ui.cpp.s
.PHONY : src/feature_scrollarea/features_scrollarea_ui.cpp.s

src/feature_scrollarea/features_scrollarea_view.o: src/feature_scrollarea/features_scrollarea_view.cpp.o

.PHONY : src/feature_scrollarea/features_scrollarea_view.o

# target to build an object file
src/feature_scrollarea/features_scrollarea_view.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/feature_scrollarea/features_scrollarea_view.cpp.o
.PHONY : src/feature_scrollarea/features_scrollarea_view.cpp.o

src/feature_scrollarea/features_scrollarea_view.i: src/feature_scrollarea/features_scrollarea_view.cpp.i

.PHONY : src/feature_scrollarea/features_scrollarea_view.i

# target to preprocess a source file
src/feature_scrollarea/features_scrollarea_view.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/feature_scrollarea/features_scrollarea_view.cpp.i
.PHONY : src/feature_scrollarea/features_scrollarea_view.cpp.i

src/feature_scrollarea/features_scrollarea_view.s: src/feature_scrollarea/features_scrollarea_view.cpp.s

.PHONY : src/feature_scrollarea/features_scrollarea_view.s

# target to generate assembly for a file
src/feature_scrollarea/features_scrollarea_view.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/feature_scrollarea/features_scrollarea_view.cpp.s
.PHONY : src/feature_scrollarea/features_scrollarea_view.cpp.s

src/feature_value_widgets/value_2button_widget.o: src/feature_value_widgets/value_2button_widget.cpp.o

.PHONY : src/feature_value_widgets/value_2button_widget.o

# target to build an object file
src/feature_value_widgets/value_2button_widget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/feature_value_widgets/value_2button_widget.cpp.o
.PHONY : src/feature_value_widgets/value_2button_widget.cpp.o

src/feature_value_widgets/value_2button_widget.i: src/feature_value_widgets/value_2button_widget.cpp.i

.PHONY : src/feature_value_widgets/value_2button_widget.i

# target to preprocess a source file
src/feature_value_widgets/value_2button_widget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/feature_value_widgets/value_2button_widget.cpp.i
.PHONY : src/feature_value_widgets/value_2button_widget.cpp.i

src/feature_value_widgets/value_2button_widget.s: src/feature_value_widgets/value_2button_widget.cpp.s

.PHONY : src/feature_value_widgets/value_2button_widget.s

# target to generate assembly for a file
src/feature_value_widgets/value_2button_widget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/feature_value_widgets/value_2button_widget.cpp.s
.PHONY : src/feature_value_widgets/value_2button_widget.cpp.s

src/feature_value_widgets/value_base_widget.o: src/feature_value_widgets/value_base_widget.cpp.o

.PHONY : src/feature_value_widgets/value_base_widget.o

# target to build an object file
src/feature_value_widgets/value_base_widget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/feature_value_widgets/value_base_widget.cpp.o
.PHONY : src/feature_value_widgets/value_base_widget.cpp.o

src/feature_value_widgets/value_base_widget.i: src/feature_value_widgets/value_base_widget.cpp.i

.PHONY : src/feature_value_widgets/value_base_widget.i

# target to preprocess a source file
src/feature_value_widgets/value_base_widget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/feature_value_widgets/value_base_widget.cpp.i
.PHONY : src/feature_value_widgets/value_base_widget.cpp.i

src/feature_value_widgets/value_base_widget.s: src/feature_value_widgets/value_base_widget.cpp.s

.PHONY : src/feature_value_widgets/value_base_widget.s

# target to generate assembly for a file
src/feature_value_widgets/value_base_widget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/feature_value_widgets/value_base_widget.cpp.s
.PHONY : src/feature_value_widgets/value_base_widget.cpp.s

src/feature_value_widgets/value_bytes_widget.o: src/feature_value_widgets/value_bytes_widget.cpp.o

.PHONY : src/feature_value_widgets/value_bytes_widget.o

# target to build an object file
src/feature_value_widgets/value_bytes_widget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/feature_value_widgets/value_bytes_widget.cpp.o
.PHONY : src/feature_value_widgets/value_bytes_widget.cpp.o

src/feature_value_widgets/value_bytes_widget.i: src/feature_value_widgets/value_bytes_widget.cpp.i

.PHONY : src/feature_value_widgets/value_bytes_widget.i

# target to preprocess a source file
src/feature_value_widgets/value_bytes_widget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/feature_value_widgets/value_bytes_widget.cpp.i
.PHONY : src/feature_value_widgets/value_bytes_widget.cpp.i

src/feature_value_widgets/value_bytes_widget.s: src/feature_value_widgets/value_bytes_widget.cpp.s

.PHONY : src/feature_value_widgets/value_bytes_widget.s

# target to generate assembly for a file
src/feature_value_widgets/value_bytes_widget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/feature_value_widgets/value_bytes_widget.cpp.s
.PHONY : src/feature_value_widgets/value_bytes_widget.cpp.s

src/feature_value_widgets/value_cnc_widget_x14.o: src/feature_value_widgets/value_cnc_widget_x14.cpp.o

.PHONY : src/feature_value_widgets/value_cnc_widget_x14.o

# target to build an object file
src/feature_value_widgets/value_cnc_widget_x14.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/feature_value_widgets/value_cnc_widget_x14.cpp.o
.PHONY : src/feature_value_widgets/value_cnc_widget_x14.cpp.o

src/feature_value_widgets/value_cnc_widget_x14.i: src/feature_value_widgets/value_cnc_widget_x14.cpp.i

.PHONY : src/feature_value_widgets/value_cnc_widget_x14.i

# target to preprocess a source file
src/feature_value_widgets/value_cnc_widget_x14.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/feature_value_widgets/value_cnc_widget_x14.cpp.i
.PHONY : src/feature_value_widgets/value_cnc_widget_x14.cpp.i

src/feature_value_widgets/value_cnc_widget_x14.s: src/feature_value_widgets/value_cnc_widget_x14.cpp.s

.PHONY : src/feature_value_widgets/value_cnc_widget_x14.s

# target to generate assembly for a file
src/feature_value_widgets/value_cnc_widget_x14.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/feature_value_widgets/value_cnc_widget_x14.cpp.s
.PHONY : src/feature_value_widgets/value_cnc_widget_x14.cpp.s

src/feature_value_widgets/value_cont_widget.o: src/feature_value_widgets/value_cont_widget.cpp.o

.PHONY : src/feature_value_widgets/value_cont_widget.o

# target to build an object file
src/feature_value_widgets/value_cont_widget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/feature_value_widgets/value_cont_widget.cpp.o
.PHONY : src/feature_value_widgets/value_cont_widget.cpp.o

src/feature_value_widgets/value_cont_widget.i: src/feature_value_widgets/value_cont_widget.cpp.i

.PHONY : src/feature_value_widgets/value_cont_widget.i

# target to preprocess a source file
src/feature_value_widgets/value_cont_widget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/feature_value_widgets/value_cont_widget.cpp.i
.PHONY : src/feature_value_widgets/value_cont_widget.cpp.i

src/feature_value_widgets/value_cont_widget.s: src/feature_value_widgets/value_cont_widget.cpp.s

.PHONY : src/feature_value_widgets/value_cont_widget.s

# target to generate assembly for a file
src/feature_value_widgets/value_cont_widget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/feature_value_widgets/value_cont_widget.cpp.s
.PHONY : src/feature_value_widgets/value_cont_widget.cpp.s

src/feature_value_widgets/value_nc_widget.o: src/feature_value_widgets/value_nc_widget.cpp.o

.PHONY : src/feature_value_widgets/value_nc_widget.o

# target to build an object file
src/feature_value_widgets/value_nc_widget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/feature_value_widgets/value_nc_widget.cpp.o
.PHONY : src/feature_value_widgets/value_nc_widget.cpp.o

src/feature_value_widgets/value_nc_widget.i: src/feature_value_widgets/value_nc_widget.cpp.i

.PHONY : src/feature_value_widgets/value_nc_widget.i

# target to preprocess a source file
src/feature_value_widgets/value_nc_widget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/feature_value_widgets/value_nc_widget.cpp.i
.PHONY : src/feature_value_widgets/value_nc_widget.cpp.i

src/feature_value_widgets/value_nc_widget.s: src/feature_value_widgets/value_nc_widget.cpp.s

.PHONY : src/feature_value_widgets/value_nc_widget.s

# target to generate assembly for a file
src/feature_value_widgets/value_nc_widget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/feature_value_widgets/value_nc_widget.cpp.s
.PHONY : src/feature_value_widgets/value_nc_widget.cpp.s

src/feature_value_widgets/value_ncplus_widget.o: src/feature_value_widgets/value_ncplus_widget.cpp.o

.PHONY : src/feature_value_widgets/value_ncplus_widget.o

# target to build an object file
src/feature_value_widgets/value_ncplus_widget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/feature_value_widgets/value_ncplus_widget.cpp.o
.PHONY : src/feature_value_widgets/value_ncplus_widget.cpp.o

src/feature_value_widgets/value_ncplus_widget.i: src/feature_value_widgets/value_ncplus_widget.cpp.i

.PHONY : src/feature_value_widgets/value_ncplus_widget.i

# target to preprocess a source file
src/feature_value_widgets/value_ncplus_widget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/feature_value_widgets/value_ncplus_widget.cpp.i
.PHONY : src/feature_value_widgets/value_ncplus_widget.cpp.i

src/feature_value_widgets/value_ncplus_widget.s: src/feature_value_widgets/value_ncplus_widget.cpp.s

.PHONY : src/feature_value_widgets/value_ncplus_widget.s

# target to generate assembly for a file
src/feature_value_widgets/value_ncplus_widget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/feature_value_widgets/value_ncplus_widget.cpp.s
.PHONY : src/feature_value_widgets/value_ncplus_widget.cpp.s

src/feature_value_widgets/value_reset_widget.o: src/feature_value_widgets/value_reset_widget.cpp.o

.PHONY : src/feature_value_widgets/value_reset_widget.o

# target to build an object file
src/feature_value_widgets/value_reset_widget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/feature_value_widgets/value_reset_widget.cpp.o
.PHONY : src/feature_value_widgets/value_reset_widget.cpp.o

src/feature_value_widgets/value_reset_widget.i: src/feature_value_widgets/value_reset_widget.cpp.i

.PHONY : src/feature_value_widgets/value_reset_widget.i

# target to preprocess a source file
src/feature_value_widgets/value_reset_widget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/feature_value_widgets/value_reset_widget.cpp.i
.PHONY : src/feature_value_widgets/value_reset_widget.cpp.i

src/feature_value_widgets/value_reset_widget.s: src/feature_value_widgets/value_reset_widget.cpp.s

.PHONY : src/feature_value_widgets/value_reset_widget.s

# target to generate assembly for a file
src/feature_value_widgets/value_reset_widget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/feature_value_widgets/value_reset_widget.cpp.s
.PHONY : src/feature_value_widgets/value_reset_widget.cpp.s

src/feature_value_widgets/value_stacked_widget.o: src/feature_value_widgets/value_stacked_widget.cpp.o

.PHONY : src/feature_value_widgets/value_stacked_widget.o

# target to build an object file
src/feature_value_widgets/value_stacked_widget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/feature_value_widgets/value_stacked_widget.cpp.o
.PHONY : src/feature_value_widgets/value_stacked_widget.cpp.o

src/feature_value_widgets/value_stacked_widget.i: src/feature_value_widgets/value_stacked_widget.cpp.i

.PHONY : src/feature_value_widgets/value_stacked_widget.i

# target to preprocess a source file
src/feature_value_widgets/value_stacked_widget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/feature_value_widgets/value_stacked_widget.cpp.i
.PHONY : src/feature_value_widgets/value_stacked_widget.cpp.i

src/feature_value_widgets/value_stacked_widget.s: src/feature_value_widgets/value_stacked_widget.cpp.s

.PHONY : src/feature_value_widgets/value_stacked_widget.s

# target to generate assembly for a file
src/feature_value_widgets/value_stacked_widget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/feature_value_widgets/value_stacked_widget.cpp.s
.PHONY : src/feature_value_widgets/value_stacked_widget.cpp.s

src/feature_value_widgets/value_std_widget.o: src/feature_value_widgets/value_std_widget.cpp.o

.PHONY : src/feature_value_widgets/value_std_widget.o

# target to build an object file
src/feature_value_widgets/value_std_widget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/feature_value_widgets/value_std_widget.cpp.o
.PHONY : src/feature_value_widgets/value_std_widget.cpp.o

src/feature_value_widgets/value_std_widget.i: src/feature_value_widgets/value_std_widget.cpp.i

.PHONY : src/feature_value_widgets/value_std_widget.i

# target to preprocess a source file
src/feature_value_widgets/value_std_widget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/feature_value_widgets/value_std_widget.cpp.i
.PHONY : src/feature_value_widgets/value_std_widget.cpp.i

src/feature_value_widgets/value_std_widget.s: src/feature_value_widgets/value_std_widget.cpp.s

.PHONY : src/feature_value_widgets/value_std_widget.s

# target to generate assembly for a file
src/feature_value_widgets/value_std_widget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/feature_value_widgets/value_std_widget.cpp.s
.PHONY : src/feature_value_widgets/value_std_widget.cpp.s

src/help/help_dialog.o: src/help/help_dialog.cpp.o

.PHONY : src/help/help_dialog.o

# target to build an object file
src/help/help_dialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/help/help_dialog.cpp.o
.PHONY : src/help/help_dialog.cpp.o

src/help/help_dialog.i: src/help/help_dialog.cpp.i

.PHONY : src/help/help_dialog.i

# target to preprocess a source file
src/help/help_dialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/help/help_dialog.cpp.i
.PHONY : src/help/help_dialog.cpp.i

src/help/help_dialog.s: src/help/help_dialog.cpp.s

.PHONY : src/help/help_dialog.s

# target to generate assembly for a file
src/help/help_dialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/help/help_dialog.cpp.s
.PHONY : src/help/help_dialog.cpp.s

src/main/main.o: src/main/main.cpp.o

.PHONY : src/main/main.o

# target to build an object file
src/main/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/main/main.cpp.o
.PHONY : src/main/main.cpp.o

src/main/main.i: src/main/main.cpp.i

.PHONY : src/main/main.i

# target to preprocess a source file
src/main/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/main/main.cpp.i
.PHONY : src/main/main.cpp.i

src/main/main.s: src/main/main.cpp.s

.PHONY : src/main/main.s

# target to generate assembly for a file
src/main/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/main/main.cpp.s
.PHONY : src/main/main.cpp.s

src/main/mainwindow.o: src/main/mainwindow.cpp.o

.PHONY : src/main/mainwindow.o

# target to build an object file
src/main/mainwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/main/mainwindow.cpp.o
.PHONY : src/main/mainwindow.cpp.o

src/main/mainwindow.i: src/main/mainwindow.cpp.i

.PHONY : src/main/mainwindow.i

# target to preprocess a source file
src/main/mainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/main/mainwindow.cpp.i
.PHONY : src/main/mainwindow.cpp.i

src/main/mainwindow.s: src/main/mainwindow.cpp.s

.PHONY : src/main/mainwindow.s

# target to generate assembly for a file
src/main/mainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/main/mainwindow.cpp.s
.PHONY : src/main/mainwindow.cpp.s

src/main/mainwindow_ui.o: src/main/mainwindow_ui.cpp.o

.PHONY : src/main/mainwindow_ui.o

# target to build an object file
src/main/mainwindow_ui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/main/mainwindow_ui.cpp.o
.PHONY : src/main/mainwindow_ui.cpp.o

src/main/mainwindow_ui.i: src/main/mainwindow_ui.cpp.i

.PHONY : src/main/mainwindow_ui.i

# target to preprocess a source file
src/main/mainwindow_ui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/main/mainwindow_ui.cpp.i
.PHONY : src/main/mainwindow_ui.cpp.i

src/main/mainwindow_ui.s: src/main/mainwindow_ui.cpp.s

.PHONY : src/main/mainwindow_ui.s

# target to generate assembly for a file
src/main/mainwindow_ui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/main/mainwindow_ui.cpp.s
.PHONY : src/main/mainwindow_ui.cpp.s

src/main/monitor.o: src/main/monitor.cpp.o

.PHONY : src/main/monitor.o

# target to build an object file
src/main/monitor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/main/monitor.cpp.o
.PHONY : src/main/monitor.cpp.o

src/main/monitor.i: src/main/monitor.cpp.i

.PHONY : src/main/monitor.i

# target to preprocess a source file
src/main/monitor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/main/monitor.cpp.i
.PHONY : src/main/monitor.cpp.i

src/main/monitor.s: src/main/monitor.cpp.s

.PHONY : src/main/monitor.s

# target to generate assembly for a file
src/main/monitor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/main/monitor.cpp.s
.PHONY : src/main/monitor.cpp.s

src/main/msgbox_thread.o: src/main/msgbox_thread.cpp.o

.PHONY : src/main/msgbox_thread.o

# target to build an object file
src/main/msgbox_thread.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/main/msgbox_thread.cpp.o
.PHONY : src/main/msgbox_thread.cpp.o

src/main/msgbox_thread.i: src/main/msgbox_thread.cpp.i

.PHONY : src/main/msgbox_thread.i

# target to preprocess a source file
src/main/msgbox_thread.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/main/msgbox_thread.cpp.i
.PHONY : src/main/msgbox_thread.cpp.i

src/main/msgbox_thread.s: src/main/msgbox_thread.cpp.s

.PHONY : src/main/msgbox_thread.s

# target to generate assembly for a file
src/main/msgbox_thread.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/main/msgbox_thread.cpp.s
.PHONY : src/main/msgbox_thread.cpp.s

src/monitor_desc/monitor_desc_actions.o: src/monitor_desc/monitor_desc_actions.cpp.o

.PHONY : src/monitor_desc/monitor_desc_actions.o

# target to build an object file
src/monitor_desc/monitor_desc_actions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/monitor_desc/monitor_desc_actions.cpp.o
.PHONY : src/monitor_desc/monitor_desc_actions.cpp.o

src/monitor_desc/monitor_desc_actions.i: src/monitor_desc/monitor_desc_actions.cpp.i

.PHONY : src/monitor_desc/monitor_desc_actions.i

# target to preprocess a source file
src/monitor_desc/monitor_desc_actions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/monitor_desc/monitor_desc_actions.cpp.i
.PHONY : src/monitor_desc/monitor_desc_actions.cpp.i

src/monitor_desc/monitor_desc_actions.s: src/monitor_desc/monitor_desc_actions.cpp.s

.PHONY : src/monitor_desc/monitor_desc_actions.s

# target to generate assembly for a file
src/monitor_desc/monitor_desc_actions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/monitor_desc/monitor_desc_actions.cpp.s
.PHONY : src/monitor_desc/monitor_desc_actions.cpp.s

src/monitor_desc/monitor_desc_ui.o: src/monitor_desc/monitor_desc_ui.cpp.o

.PHONY : src/monitor_desc/monitor_desc_ui.o

# target to build an object file
src/monitor_desc/monitor_desc_ui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/monitor_desc/monitor_desc_ui.cpp.o
.PHONY : src/monitor_desc/monitor_desc_ui.cpp.o

src/monitor_desc/monitor_desc_ui.i: src/monitor_desc/monitor_desc_ui.cpp.i

.PHONY : src/monitor_desc/monitor_desc_ui.i

# target to preprocess a source file
src/monitor_desc/monitor_desc_ui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/monitor_desc/monitor_desc_ui.cpp.i
.PHONY : src/monitor_desc/monitor_desc_ui.cpp.i

src/monitor_desc/monitor_desc_ui.s: src/monitor_desc/monitor_desc_ui.cpp.s

.PHONY : src/monitor_desc/monitor_desc_ui.s

# target to generate assembly for a file
src/monitor_desc/monitor_desc_ui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/monitor_desc/monitor_desc_ui.cpp.s
.PHONY : src/monitor_desc/monitor_desc_ui.cpp.s

src/nongui/ddc_error.o: src/nongui/ddc_error.cpp.o

.PHONY : src/nongui/ddc_error.o

# target to build an object file
src/nongui/ddc_error.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/nongui/ddc_error.cpp.o
.PHONY : src/nongui/ddc_error.cpp.o

src/nongui/ddc_error.i: src/nongui/ddc_error.cpp.i

.PHONY : src/nongui/ddc_error.i

# target to preprocess a source file
src/nongui/ddc_error.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/nongui/ddc_error.cpp.i
.PHONY : src/nongui/ddc_error.cpp.i

src/nongui/ddc_error.s: src/nongui/ddc_error.cpp.s

.PHONY : src/nongui/ddc_error.s

# target to generate assembly for a file
src/nongui/ddc_error.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/nongui/ddc_error.cpp.s
.PHONY : src/nongui/ddc_error.cpp.s

src/nongui/feature_base_model.o: src/nongui/feature_base_model.cpp.o

.PHONY : src/nongui/feature_base_model.o

# target to build an object file
src/nongui/feature_base_model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/nongui/feature_base_model.cpp.o
.PHONY : src/nongui/feature_base_model.cpp.o

src/nongui/feature_base_model.i: src/nongui/feature_base_model.cpp.i

.PHONY : src/nongui/feature_base_model.i

# target to preprocess a source file
src/nongui/feature_base_model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/nongui/feature_base_model.cpp.i
.PHONY : src/nongui/feature_base_model.cpp.i

src/nongui/feature_base_model.s: src/nongui/feature_base_model.cpp.s

.PHONY : src/nongui/feature_base_model.s

# target to generate assembly for a file
src/nongui/feature_base_model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/nongui/feature_base_model.cpp.s
.PHONY : src/nongui/feature_base_model.cpp.s

src/nongui/feature_value.o: src/nongui/feature_value.cpp.o

.PHONY : src/nongui/feature_value.o

# target to build an object file
src/nongui/feature_value.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/nongui/feature_value.cpp.o
.PHONY : src/nongui/feature_value.cpp.o

src/nongui/feature_value.i: src/nongui/feature_value.cpp.i

.PHONY : src/nongui/feature_value.i

# target to preprocess a source file
src/nongui/feature_value.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/nongui/feature_value.cpp.i
.PHONY : src/nongui/feature_value.cpp.i

src/nongui/feature_value.s: src/nongui/feature_value.cpp.s

.PHONY : src/nongui/feature_value.s

# target to generate assembly for a file
src/nongui/feature_value.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/nongui/feature_value.cpp.s
.PHONY : src/nongui/feature_value.cpp.s

src/nongui/msgbox_queue.o: src/nongui/msgbox_queue.cpp.o

.PHONY : src/nongui/msgbox_queue.o

# target to build an object file
src/nongui/msgbox_queue.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/nongui/msgbox_queue.cpp.o
.PHONY : src/nongui/msgbox_queue.cpp.o

src/nongui/msgbox_queue.i: src/nongui/msgbox_queue.cpp.i

.PHONY : src/nongui/msgbox_queue.i

# target to preprocess a source file
src/nongui/msgbox_queue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/nongui/msgbox_queue.cpp.i
.PHONY : src/nongui/msgbox_queue.cpp.i

src/nongui/msgbox_queue.s: src/nongui/msgbox_queue.cpp.s

.PHONY : src/nongui/msgbox_queue.s

# target to generate assembly for a file
src/nongui/msgbox_queue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/nongui/msgbox_queue.cpp.s
.PHONY : src/nongui/msgbox_queue.cpp.s

src/nongui/vcprequest.o: src/nongui/vcprequest.cpp.o

.PHONY : src/nongui/vcprequest.o

# target to build an object file
src/nongui/vcprequest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/nongui/vcprequest.cpp.o
.PHONY : src/nongui/vcprequest.cpp.o

src/nongui/vcprequest.i: src/nongui/vcprequest.cpp.i

.PHONY : src/nongui/vcprequest.i

# target to preprocess a source file
src/nongui/vcprequest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/nongui/vcprequest.cpp.i
.PHONY : src/nongui/vcprequest.cpp.i

src/nongui/vcprequest.s: src/nongui/vcprequest.cpp.s

.PHONY : src/nongui/vcprequest.s

# target to generate assembly for a file
src/nongui/vcprequest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/nongui/vcprequest.cpp.s
.PHONY : src/nongui/vcprequest.cpp.s

src/nongui/vcpthread.o: src/nongui/vcpthread.cpp.o

.PHONY : src/nongui/vcpthread.o

# target to build an object file
src/nongui/vcpthread.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/nongui/vcpthread.cpp.o
.PHONY : src/nongui/vcpthread.cpp.o

src/nongui/vcpthread.i: src/nongui/vcpthread.cpp.i

.PHONY : src/nongui/vcpthread.i

# target to preprocess a source file
src/nongui/vcpthread.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/nongui/vcpthread.cpp.i
.PHONY : src/nongui/vcpthread.cpp.i

src/nongui/vcpthread.s: src/nongui/vcpthread.cpp.s

.PHONY : src/nongui/vcpthread.s

# target to generate assembly for a file
src/nongui/vcpthread.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/nongui/vcpthread.cpp.s
.PHONY : src/nongui/vcpthread.cpp.s

src/option_dialogs/feature_selection_dialog.o: src/option_dialogs/feature_selection_dialog.cpp.o

.PHONY : src/option_dialogs/feature_selection_dialog.o

# target to build an object file
src/option_dialogs/feature_selection_dialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/option_dialogs/feature_selection_dialog.cpp.o
.PHONY : src/option_dialogs/feature_selection_dialog.cpp.o

src/option_dialogs/feature_selection_dialog.i: src/option_dialogs/feature_selection_dialog.cpp.i

.PHONY : src/option_dialogs/feature_selection_dialog.i

# target to preprocess a source file
src/option_dialogs/feature_selection_dialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/option_dialogs/feature_selection_dialog.cpp.i
.PHONY : src/option_dialogs/feature_selection_dialog.cpp.i

src/option_dialogs/feature_selection_dialog.s: src/option_dialogs/feature_selection_dialog.cpp.s

.PHONY : src/option_dialogs/feature_selection_dialog.s

# target to generate assembly for a file
src/option_dialogs/feature_selection_dialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/option_dialogs/feature_selection_dialog.cpp.s
.PHONY : src/option_dialogs/feature_selection_dialog.cpp.s

src/option_dialogs/other_options_dialog.o: src/option_dialogs/other_options_dialog.cpp.o

.PHONY : src/option_dialogs/other_options_dialog.o

# target to build an object file
src/option_dialogs/other_options_dialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/option_dialogs/other_options_dialog.cpp.o
.PHONY : src/option_dialogs/other_options_dialog.cpp.o

src/option_dialogs/other_options_dialog.i: src/option_dialogs/other_options_dialog.cpp.i

.PHONY : src/option_dialogs/other_options_dialog.i

# target to preprocess a source file
src/option_dialogs/other_options_dialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/option_dialogs/other_options_dialog.cpp.i
.PHONY : src/option_dialogs/other_options_dialog.cpp.i

src/option_dialogs/other_options_dialog.s: src/option_dialogs/other_options_dialog.cpp.s

.PHONY : src/option_dialogs/other_options_dialog.s

# target to generate assembly for a file
src/option_dialogs/other_options_dialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/option_dialogs/other_options_dialog.cpp.s
.PHONY : src/option_dialogs/other_options_dialog.cpp.s

src/option_dialogs/user_interface_options_dialog.o: src/option_dialogs/user_interface_options_dialog.cpp.o

.PHONY : src/option_dialogs/user_interface_options_dialog.o

# target to build an object file
src/option_dialogs/user_interface_options_dialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/option_dialogs/user_interface_options_dialog.cpp.o
.PHONY : src/option_dialogs/user_interface_options_dialog.cpp.o

src/option_dialogs/user_interface_options_dialog.i: src/option_dialogs/user_interface_options_dialog.cpp.i

.PHONY : src/option_dialogs/user_interface_options_dialog.i

# target to preprocess a source file
src/option_dialogs/user_interface_options_dialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/option_dialogs/user_interface_options_dialog.cpp.i
.PHONY : src/option_dialogs/user_interface_options_dialog.cpp.i

src/option_dialogs/user_interface_options_dialog.s: src/option_dialogs/user_interface_options_dialog.cpp.s

.PHONY : src/option_dialogs/user_interface_options_dialog.s

# target to generate assembly for a file
src/option_dialogs/user_interface_options_dialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ddcui.dir/build.make CMakeFiles/ddcui.dir/src/option_dialogs/user_interface_options_dialog.cpp.s
.PHONY : src/option_dialogs/user_interface_options_dialog.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... ddcui_autogen"
	@echo "... uninstall"
	@echo "... ddcui"
	@echo "... ddcui_autogen/EWIEGA46WW/qrc_ddcui.o"
	@echo "... ddcui_autogen/EWIEGA46WW/qrc_ddcui.i"
	@echo "... ddcui_autogen/EWIEGA46WW/qrc_ddcui.s"
	@echo "... ddcui_autogen/mocs_compilation.o"
	@echo "... ddcui_autogen/mocs_compilation.i"
	@echo "... ddcui_autogen/mocs_compilation.s"
	@echo "... src/action_dialogs/debug_actions_dialog.o"
	@echo "... src/action_dialogs/debug_actions_dialog.i"
	@echo "... src/action_dialogs/debug_actions_dialog.s"
	@echo "... src/base/core.o"
	@echo "... src/base/core.i"
	@echo "... src/base/core.s"
	@echo "... src/base/ddca_utils.o"
	@echo "... src/base/ddca_utils.i"
	@echo "... src/base/ddca_utils.s"
	@echo "... src/base/ddcui_parms.o"
	@echo "... src/base/ddcui_parms.i"
	@echo "... src/base/ddcui_parms.s"
	@echo "... src/base/feature_list.o"
	@echo "... src/base/feature_list.i"
	@echo "... src/base/feature_list.s"
	@echo "... src/base/feature_selector.o"
	@echo "... src/base/feature_selector.i"
	@echo "... src/base/feature_selector.s"
	@echo "... src/base/global_state.o"
	@echo "... src/base/global_state.i"
	@echo "... src/base/global_state.s"
	@echo "... src/base/other_options_state.o"
	@echo "... src/base/other_options_state.i"
	@echo "... src/base/other_options_state.s"
	@echo "... src/base/user_interface_options_state.o"
	@echo "... src/base/user_interface_options_state.i"
	@echo "... src/base/user_interface_options_state.s"
	@echo "... src/base/widget_debug.o"
	@echo "... src/base/widget_debug.i"
	@echo "... src/base/widget_debug.s"
	@echo "... src/c_util/data_structures.o"
	@echo "... src/c_util/data_structures.i"
	@echo "... src/c_util/data_structures.s"
	@echo "... src/c_util/string_util.o"
	@echo "... src/c_util/string_util.i"
	@echo "... src/c_util/string_util.s"
	@echo "... src/cmdline/cmd_parser.o"
	@echo "... src/cmdline/cmd_parser.i"
	@echo "... src/cmdline/cmd_parser.s"
	@echo "... src/cmdline/cmd_parser_aux.o"
	@echo "... src/cmdline/cmd_parser_aux.i"
	@echo "... src/cmdline/cmd_parser_aux.s"
	@echo "... src/cmdline/parsed_cmd.o"
	@echo "... src/cmdline/parsed_cmd.i"
	@echo "... src/cmdline/parsed_cmd.s"
	@echo "... src/core_widgets/enhanced_slider.o"
	@echo "... src/core_widgets/enhanced_slider.i"
	@echo "... src/core_widgets/enhanced_slider.s"
	@echo "... src/core_widgets/hex_number_validator.o"
	@echo "... src/core_widgets/hex_number_validator.i"
	@echo "... src/core_widgets/hex_number_validator.s"
	@echo "... src/core_widgets/hline_widget.o"
	@echo "... src/core_widgets/hline_widget.i"
	@echo "... src/core_widgets/hline_widget.s"
	@echo "... src/core_widgets/number_entry_widget.o"
	@echo "... src/core_widgets/number_entry_widget.i"
	@echo "... src/core_widgets/number_entry_widget.s"
	@echo "... src/feature_scrollarea/feature_widget.o"
	@echo "... src/feature_scrollarea/feature_widget.i"
	@echo "... src/feature_scrollarea/feature_widget.s"
	@echo "... src/feature_scrollarea/feature_widget_header.o"
	@echo "... src/feature_scrollarea/feature_widget_header.i"
	@echo "... src/feature_scrollarea/feature_widget_header.s"
	@echo "... src/feature_scrollarea/features_scrollarea.o"
	@echo "... src/feature_scrollarea/features_scrollarea.i"
	@echo "... src/feature_scrollarea/features_scrollarea.s"
	@echo "... src/feature_scrollarea/features_scrollarea_contents.o"
	@echo "... src/feature_scrollarea/features_scrollarea_contents.i"
	@echo "... src/feature_scrollarea/features_scrollarea_contents.s"
	@echo "... src/feature_scrollarea/features_scrollarea_ui.o"
	@echo "... src/feature_scrollarea/features_scrollarea_ui.i"
	@echo "... src/feature_scrollarea/features_scrollarea_ui.s"
	@echo "... src/feature_scrollarea/features_scrollarea_view.o"
	@echo "... src/feature_scrollarea/features_scrollarea_view.i"
	@echo "... src/feature_scrollarea/features_scrollarea_view.s"
	@echo "... src/feature_value_widgets/value_2button_widget.o"
	@echo "... src/feature_value_widgets/value_2button_widget.i"
	@echo "... src/feature_value_widgets/value_2button_widget.s"
	@echo "... src/feature_value_widgets/value_base_widget.o"
	@echo "... src/feature_value_widgets/value_base_widget.i"
	@echo "... src/feature_value_widgets/value_base_widget.s"
	@echo "... src/feature_value_widgets/value_bytes_widget.o"
	@echo "... src/feature_value_widgets/value_bytes_widget.i"
	@echo "... src/feature_value_widgets/value_bytes_widget.s"
	@echo "... src/feature_value_widgets/value_cnc_widget_x14.o"
	@echo "... src/feature_value_widgets/value_cnc_widget_x14.i"
	@echo "... src/feature_value_widgets/value_cnc_widget_x14.s"
	@echo "... src/feature_value_widgets/value_cont_widget.o"
	@echo "... src/feature_value_widgets/value_cont_widget.i"
	@echo "... src/feature_value_widgets/value_cont_widget.s"
	@echo "... src/feature_value_widgets/value_nc_widget.o"
	@echo "... src/feature_value_widgets/value_nc_widget.i"
	@echo "... src/feature_value_widgets/value_nc_widget.s"
	@echo "... src/feature_value_widgets/value_ncplus_widget.o"
	@echo "... src/feature_value_widgets/value_ncplus_widget.i"
	@echo "... src/feature_value_widgets/value_ncplus_widget.s"
	@echo "... src/feature_value_widgets/value_reset_widget.o"
	@echo "... src/feature_value_widgets/value_reset_widget.i"
	@echo "... src/feature_value_widgets/value_reset_widget.s"
	@echo "... src/feature_value_widgets/value_stacked_widget.o"
	@echo "... src/feature_value_widgets/value_stacked_widget.i"
	@echo "... src/feature_value_widgets/value_stacked_widget.s"
	@echo "... src/feature_value_widgets/value_std_widget.o"
	@echo "... src/feature_value_widgets/value_std_widget.i"
	@echo "... src/feature_value_widgets/value_std_widget.s"
	@echo "... src/help/help_dialog.o"
	@echo "... src/help/help_dialog.i"
	@echo "... src/help/help_dialog.s"
	@echo "... src/main/main.o"
	@echo "... src/main/main.i"
	@echo "... src/main/main.s"
	@echo "... src/main/mainwindow.o"
	@echo "... src/main/mainwindow.i"
	@echo "... src/main/mainwindow.s"
	@echo "... src/main/mainwindow_ui.o"
	@echo "... src/main/mainwindow_ui.i"
	@echo "... src/main/mainwindow_ui.s"
	@echo "... src/main/monitor.o"
	@echo "... src/main/monitor.i"
	@echo "... src/main/monitor.s"
	@echo "... src/main/msgbox_thread.o"
	@echo "... src/main/msgbox_thread.i"
	@echo "... src/main/msgbox_thread.s"
	@echo "... src/monitor_desc/monitor_desc_actions.o"
	@echo "... src/monitor_desc/monitor_desc_actions.i"
	@echo "... src/monitor_desc/monitor_desc_actions.s"
	@echo "... src/monitor_desc/monitor_desc_ui.o"
	@echo "... src/monitor_desc/monitor_desc_ui.i"
	@echo "... src/monitor_desc/monitor_desc_ui.s"
	@echo "... src/nongui/ddc_error.o"
	@echo "... src/nongui/ddc_error.i"
	@echo "... src/nongui/ddc_error.s"
	@echo "... src/nongui/feature_base_model.o"
	@echo "... src/nongui/feature_base_model.i"
	@echo "... src/nongui/feature_base_model.s"
	@echo "... src/nongui/feature_value.o"
	@echo "... src/nongui/feature_value.i"
	@echo "... src/nongui/feature_value.s"
	@echo "... src/nongui/msgbox_queue.o"
	@echo "... src/nongui/msgbox_queue.i"
	@echo "... src/nongui/msgbox_queue.s"
	@echo "... src/nongui/vcprequest.o"
	@echo "... src/nongui/vcprequest.i"
	@echo "... src/nongui/vcprequest.s"
	@echo "... src/nongui/vcpthread.o"
	@echo "... src/nongui/vcpthread.i"
	@echo "... src/nongui/vcpthread.s"
	@echo "... src/option_dialogs/feature_selection_dialog.o"
	@echo "... src/option_dialogs/feature_selection_dialog.i"
	@echo "... src/option_dialogs/feature_selection_dialog.s"
	@echo "... src/option_dialogs/other_options_dialog.o"
	@echo "... src/option_dialogs/other_options_dialog.i"
	@echo "... src/option_dialogs/other_options_dialog.s"
	@echo "... src/option_dialogs/user_interface_options_dialog.o"
	@echo "... src/option_dialogs/user_interface_options_dialog.i"
	@echo "... src/option_dialogs/user_interface_options_dialog.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

